In [9]:
#Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from math import sqrt

#Loading the dataset
dataset = pd.read_csv('/content/drive/MyDrive/SEIS763ML/DataML/employee.csv')
#print(dataset)

#Extracting the independent and dependent variables
X = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

#print(X)
#print(y)

#Dealing with Categorical columns
#Removing the extra dummy variable
X = pd.get_dummies(X, columns=['Department'],drop_first= True)

#print(X)

#Encoding the dependent class variable
#from sklearn.preprocessing import LabelEncoder
#le = LabelEncoder()
#y = le.fit_transform(y)

#Converting to numpy array
X = np.array(X)
y = np.array(y)


#Splitting the data into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)


#Dealing with Missing values
#from sklearn.impute import SimpleImputer
#imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
#X_train[:, [0,1]] = imputer.fit_transform(X_train[:,[0,1]])
#X_test[:, [0,1]] = imputer.transform(X_test[:,[0,1]])

In [10]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#Fitting Multiple Linear Regression to Training Set
from sklearn.linear_model import LinearRegression
mlrObj = LinearRegression()
mlrObj.fit(X_train,y_train)

LinearRegression()

In [11]:
#Predicting on the Test Set
y_pred = mlrObj.predict(X_test)

#Backward Elimination
import statsmodels.api as sm
X = np.append(arr=np.ones((30,1)), values=X, axis=1)

# Convert to a float64
X = X.astype('float64')  # Without this, OLS function errors out

In [12]:
print(X[0:5,:])

[[1.000e+00 2.300e+03 0.000e+00 1.100e+00 0.000e+00 0.000e+00]
 [1.000e+00 2.100e+03 1.000e+00 1.300e+00 1.000e+00 0.000e+00]
 [1.000e+00 2.104e+03 2.000e+00 1.500e+00 0.000e+00 0.000e+00]
 [1.000e+00 1.200e+03 1.000e+00 2.000e+00 0.000e+00 1.000e+00]
 [1.000e+00 1.254e+03 2.000e+00 2.200e+00 1.000e+00 0.000e+00]]


In [13]:
X_sig = X[:,[0,1,2,3,4,5]]
obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.961
Model:                            OLS   Adj. R-squared:                  0.952
Method:                 Least Squares   F-statistic:                     117.2
Date:                Thu, 23 Mar 2023   Prob (F-statistic):           4.71e-16
Time:                        01:58:20   Log-Likelihood:                -300.09
No. Observations:                  30   AIC:                             612.2
Df Residuals:                      24   BIC:                             620.6
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.146e+04   4689.376      4.576      0.000    1.18e+04    3.11e+04
x1             3.3361      2.410      1.384      0.179      -1.637       8.310
x2          -423.7607   1282.271     -0.330      0.744   -3070.237    2222.716
x3          9437.2530    510.978     18.469      0.000    8382.645    1.05e+04
x4         -1421.4255   2683.353     -0.530      0.601   -6959.595    4116.744
x5            92.8656   2735.524      0.034      0.973   -5552.978    5738.710
==============================================================================
Omnibus:                        2.020   Durbin-Watson:                   1.918
Prob(Omnibus):                  0.364   Jarque-Bera (JB):                1.629
Skew:                           0.414   Prob(JB):                        0.443
Kurtosis:                       2.214   Cond. No.                     8.00e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large,  8e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [14]:
X_sig = X[:,[0,1,2,3,4]]
obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.961
Model:                            OLS   Adj. R-squared:                  0.954
Method:                 Least Squares   F-statistic:                     152.6
Date:                Thu, 23 Mar 2023   Prob (F-statistic):           3.54e-17
Time:                        01:58:20   Log-Likelihood:                -300.09
No. Observations:                  30   AIC:                             610.2
Df Residuals:                      25   BIC:                             617.2
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.151e+04   4315.092      4.986      0.000    1.26e+04    3.04e+04
x1             3.3230      2.331      1.426      0.166      -1.477       8.124
x2          -422.1845   1255.570     -0.336      0.739   -3008.079    2163.710
x3          9439.2110    497.467     18.975      0.000    8414.659    1.05e+04
x4         -1466.4735   2285.214     -0.642      0.527   -6172.961    3240.014
==============================================================================
Omnibus:                        2.056   Durbin-Watson:                   1.918
Prob(Omnibus):                  0.358   Jarque-Bera (JB):                1.630
Skew:                           0.407   Prob(JB):                        0.443
Kurtosis:                       2.200   Cond. No.                     7.20e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.2e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [15]:
X_sig = X[:,[0,1,3,4]]
obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.960
Model:                            OLS   Adj. R-squared:                  0.956
Method:                 Least Squares   F-statistic:                     210.7
Date:                Thu, 23 Mar 2023   Prob (F-statistic):           2.35e-18
Time:                        01:58:20   Log-Likelihood:                -300.16
No. Observations:                  30   AIC:                             608.3
Df Residuals:                      26   BIC:                             613.9
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.122e+04   4154.694      5.108      0.000    1.27e+04    2.98e+04
x1             3.3059      2.290      1.443      0.161      -1.402       8.014
x2          9336.1224    385.024     24.248      0.000    8544.694    1.01e+04
x3         -1479.8541   2245.558     -0.659      0.516   -6095.665    3135.956
==============================================================================
Omnibus:                        2.340   Durbin-Watson:                   1.842
Prob(Omnibus):                  0.310   Jarque-Bera (JB):                1.662
Skew:                           0.375   Prob(JB):                        0.436
Kurtosis:                       2.124   Cond. No.                     7.04e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.04e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [16]:
X_sig = X[:,[0,1,3]]
obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.960
Model:                            OLS   Adj. R-squared:                  0.957
Method:                 Least Squares   F-statistic:                     322.5
Date:                Thu, 23 Mar 2023   Prob (F-statistic):           1.42e-19
Time:                        01:58:20   Log-Likelihood:                -300.41
No. Observations:                  30   AIC:                             606.8
Df Residuals:                      27   BIC:                             611.0
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.102e+04   4099.682      5.127      0.000    1.26e+04    2.94e+04
x1             3.1236      2.250      1.389      0.176      -1.492       7.739
x2          9340.2046    380.920     24.520      0.000    8558.621    1.01e+04
==============================================================================
Omnibus:                        1.451   Durbin-Watson:                   1.842
Prob(Omnibus):                  0.484   Jarque-Bera (JB):                1.323
Skew:                           0.388   Prob(JB):                        0.516
Kurtosis:                       2.325   Cond. No.                     7.01e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.01e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [17]:
X_sig = X[:,[0,3]]
obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.957
Model:                            OLS   Adj. R-squared:                  0.955
Method:                 Least Squares   F-statistic:                     622.5
Date:                Thu, 23 Mar 2023   Prob (F-statistic):           1.14e-20
Time:                        01:58:20   Log-Likelihood:                -301.44
No. Observations:                  30   AIC:                             606.9
Df Residuals:                      28   BIC:                             609.7
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.579e+04   2273.053     11.347      0.000    2.11e+04    3.04e+04
x1          9449.9623    378.755     24.950      0.000    8674.119    1.02e+04
==============================================================================
Omnibus:                        2.140   Durbin-Watson:                   1.648
Prob(Omnibus):                  0.343   Jarque-Bera (JB):                1.569
Skew:                           0.363   Prob(JB):                        0.456
Kurtosis:                       2.147   Cond. No.                         13.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [18]:
#Retaining only years of experience column
X_train_sig = X_train[:,2:3]
X_test_sig = X_test[:,2:3]

#Building a model with significant predictor
mlrObj_sig = LinearRegression()
mlrObj_sig.fit(X_train_sig, y_train)
y_sig_pred = mlrObj_sig.predict(X_test_sig)

#Calculating MSE and RMSE with all features
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print('mean squared error', mse)
print('root mean squared error', sqrt(mse))

#Calculating MSE and RMSE with only significant predictors
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_sig_pred)
print('mean squared error', mse)
print('root mean squared error', sqrt(mse))

mean squared error 29601594.09795576
root mean squared error 5440.734702037562
mean squared error 23370078.80083297
root mean squared error 4834.2609363617275
